agente/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = "agente"

app_patterns = (
    [
        path("", views.inicio, name="inicio"),
        path("_iniciar_agente/", views.iniciar_agente, name="iniciar_agente"),
        path("_health_check/", views.agente_health_check, name="agente_health_check"),
        path("tareas/", views.tareas, name="tareas"),
        path("ver_tarea/<int:id>/", views.ver_tarea, name="ver_tarea"),
        path("imprimir_voucher/<int:id>/", views.imprimir_voucher, name="imprimir_voucher"),
        path("preview_voucher/<int:id>/", views.preview_voucher, name="preview_voucher"),
        path("log/agente/", views.log_agente, name="log_agente"),
        path(
            "configuracion_inicial/",
            views.configuracion_inicial,
            name="configuracion_inicial",
        ),
        path(
            "eliminar_configuracion", 
            views.eliminar_configuracion, 
            name="eliminar_configuracion"
        ),
        path(
            "notificar_resultado_tarea/<int:pk>/", 
            views.notificar_resultado_tarea, 
            name="notificar_resultado_tarea"
        ),

        path(
            "banorte_cargar_llave_pinpad/", 
            views.banorte_cargar_llave_pinpad, 
            name="banorte_cargar_llave_pinpad"
        ),

        path(
            "validar_ultima_version/", 
            views.validar_ultima_version, 
            name="validar_ultima_version"
        ),

        path(
            "guia_actualizacion/", 
            views.guia_actualizacion, 
            name="guia_actualizacion"
        ),
        
        path(
            "abrir_explorador_archivos/", 
            views.abrir_explorador_archivos, 
            name="abrir_explorador_archivos"
        ),
        path(
            "detener_agente/", 
            views.detener_agente, 
            name="detener_agente"
        ),
        path(
            "eliminar_configuracion_impresion/", 
            views.eliminar_configuracion_impresion, 
            name="eliminar_configuracion_impresion"
        ),
        path(
            "guia_configuracion_banorte/", 
            views.guia_configuracion_banorte, 
            name="guia_configuracion_banorte"
        ),
        path(
            "nt_solicitud_lectura_lectura_huella/", 
            views.nt_solicitud_lectura_lectura_huella, 
            name="nt_solicitud_lectura_lectura_huella"
        ),
        path(
            "ajax/obtener_impresoras/", 
            views.ajax_obtener_impresoras, 
            name="ajax_obtener_impresoras"
        ),
        path(
            "ajax/get_dispositivos_biometricos/", 
            views.ajax_get_dispositivos_biometricos, 
            name="ajax_get_dispositivos_biometricos"
        ),
        path(
            "test_sentry/", 
            views.test_sentry, 
            name="test_sentry"
        ),
    ],
    "agente",
)

urlpatterns = [
    path("", include(app_patterns)),
    path("sh/", include("sh.urls")),
    path('su/', admin.site.urls),
] 
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

agente/views.py
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from .forms import (
    ConfiguracionInicialForm,
    ConfiguracionPinpadBanorteForm,
    ConfiguracionBiometricoForm,
    ConfiguracionBasculaForm,
    ConfiguracionGeneralForm,
)
from utils.forms import EMPTY_CHOICE
from .models import ConfiguracionGeneral, Tarea
from django.utils import timezone
from django.http import JsonResponse
from django.conf import settings
from utils.functions import list_view, tail_file, log
from django.urls import reverse
import os
import json
import requests
from bootstrap import StoppableThread, start_agent
from django.views.decorators.csrf import csrf_exempt
from scripts.installer import get_last_tag_version


AGENTE_THREAD = None

def get_almacenes(configuracion):
    try:
        url_admintotal = settings.ADMINTOTAL_URL.format(configuracion.clave)
        url = f"{url_admintotal}/api/v2/almacenes/"
        return requests.get(
            url, 
            headers={"Agente": configuracion.token, "Version-Agente": settings.VERSION}, 
            timeout=5,
        ).json().get("results")
    except Exception as e:
        return []

def get_configuracion():
    try:
        return ConfiguracionGeneral.objects.get()
    except Exception as e:
        return ConfiguracionGeneral.objects.create()


def eliminar_configuracion(request):
    conf = ConfiguracionGeneral.objects.first()
    conf.clave = None
    conf.token = None
    conf.fecha_configuracion = None
    conf.redis_url = None
    conf.save()
    return redirect("agente:inicio")


def configuracion_inicial(request):
    form = ConfiguracionInicialForm()
    if request.method == "POST":
        form = ConfiguracionInicialForm(request.POST)
        if form.is_valid():
            configuracion = get_configuracion()
            
            if not configuracion:
                configuracion = ConfiguracionGeneral()
            
            configuracion.clave = form.cleaned_data.get("clave")
            configuracion.token = form.cleaned_data.get("token")
            configuracion.redis_url = form.cleaned_data.get("redis_url")
            configuracion.nombre_agente = form.cleaned_data.get("nombre_agente")
            configuracion.razon_social = form.cleaned_data.get("razon_social")
            configuracion.rfc = form.cleaned_data.get("rfc")
            configuracion.fecha_configuracion = timezone.now()
            configuracion.save()
            
            thread_start_agent = StoppableThread(target=start_agent)
            thread_start_agent.start()
            return redirect("agente:inicio")

    return render(
        request,
        "agente/configuracion_inicial.html",
        {"form": form, "title": "Configuración inicial"},
    )


def inicio(request):
    from serial.tools import list_ports

    com_ports = list_ports.comports()
    form_general = ConfiguracionGeneralForm(instance=request.configuracion)
    form_bascula = ConfiguracionBasculaForm(instance=request.configuracion)
    form_banorte = ConfiguracionPinpadBanorteForm(instance=request.configuracion)
    form_biometrico = ConfiguracionBiometricoForm(instance=request.configuracion)
    
    form_banorte.fields["banorte_puerto_pinpad"].choices = EMPTY_CHOICE + [[x.device, x.description] for x in com_ports]
    form_bascula.fields["bascula_puerto"].choices = EMPTY_CHOICE + [[x.device, x.description] for x in com_ports]

    almacenes = []
    ultimas_tareas = Tarea.objects.filter(token=request.configuracion.token)[:10]
    form_submitted = None
    configuraciones_impresora_existente = os.path.exists(settings.PATH_CONFIGURACION_IMPRESION)

    if request.method == "POST":
        form_submitted = request.POST.get("form_submitted")

        if form_submitted == "general":
            form_general = ConfiguracionGeneralForm(
                request.POST, 
                request.FILES, 
                instance=request.configuracion
            )

            if form_general.is_valid():
                form_general.save()
                messages.success(request, "Los datos han sido guardados correctamente")
                configuraciones_impresora = form_general.cleaned_data.get("configuraciones_impresora")

                if configuraciones_impresora:                    
                    with open(settings.PATH_CONFIGURACION_IMPRESION, "wb") as output:
                        output.write(configuraciones_impresora.read())

                return redirect(
                    f"{request.path}?form_submitted={form_submitted}"
                )
        
        if form_submitted == "bascula":
            form_bascula = ConfiguracionBasculaForm(
                request.POST, instance=request.configuracion
            )
            form_bascula.fields["bascula_puerto"].choices = [[x.device, x.description] for x in com_ports]

            if form_bascula.is_valid():
                form_bascula.save()
                messages.success(request, "Los datos han sido guardados correctamente")
                return redirect(
                    f"{request.path}?form_submitted={form_submitted}"
                )
        if form_submitted == "biometrico":
            form_biometrico = ConfiguracionBiometricoForm(
                request.POST, instance=request.configuracion
            )

            if form_biometrico.is_valid():
                form_biometrico.save()
                messages.success(request, "Los datos han sido guardados correctamente")
                return redirect(
                    f"{request.path}?form_submitted={form_submitted}"
                )

        if form_submitted == "banorte":
            form_banorte = ConfiguracionPinpadBanorteForm(
                request.POST, instance=request.configuracion
            )
            form_banorte.fields["banorte_puerto_pinpad"].choices = [[x.device, x.description] for x in com_ports]
            if form_banorte.is_valid():
                form_banorte.save()
                messages.success(request, "Los datos han sido guardados correctamente")
                return redirect(
                    f"{request.path}?form_submitted={form_submitted}"
                )
        
        messages.error(request, "Corrija los errores para continuar")
    else:
        almacenes = get_almacenes(request.configuracion)

    return render(
        request,
        "agente/inicio.html",
        {
            "title": "Inicio",
            "form_biometrico": form_biometrico,
            "form_banorte": form_banorte,
            "form_bascula": form_bascula,
            "form_general": form_general,
            "ultimas_tareas": ultimas_tareas,
            "form_submitted": form_submitted,
            "almacenes": almacenes,
            "configuraciones_impresora_existente": configuraciones_impresora_existente,
        },
    )


def tareas(request):
    objects = Tarea.objects.filter(token=request.configuracion.token)
    return list_view(request, objects, "agente/tareas.html", {"title": "Tareas"})

def ver_tarea(request, id):
    tarea = get_object_or_404(Tarea, token=request.configuracion.token, id=id)
    return render(
        request,
        "agente/ver_tarea.html",
        {
            "title": f"{tarea.descripcion}",
            "tarea": tarea,
            "json_data": json.dumps(tarea.to_dict(ocultar_datos=True), indent=4),
            "transaccion_banorte": tarea.get_datos().get("codigo") in [1, 5]
        },
    )

def log_agente(request):
    from agente.functions import get_logs, get_log_file_path

    max_lines = int(request.GET.get("tail") or 100)
    log_str = get_logs(max_lines)
    
    if request.is_ajax():
        return JsonResponse({
            "log": log_str,
        })
    
    return render(
        request,
        "agente/logs.html",
        {
            "title": "Logs",
            "log": log_str,
            "log_file": get_log_file_path(),
        },
    )


def notificar_resultado_tarea(request, pk):
    tarea_instance = get_object_or_404(
        Tarea, pk=pk, resultado_notificado=False
    )
    tarea_instance.enviar_resultado_admintotal(
        configuracion=request.configuracion
    )
    return redirect("agente:inicio")


def banorte_cargar_llave_pinpad(request):
    from .functions import get_instance_banorte
    try:
        pinpad = get_instance_banorte()
        pinpad.cargar_llave()
        messages.success(request, "La llave ha sido cargada correctamente")
    except Exception as e:

        if "FileNotFoundException" in str(type(e)):
            messages.error(
                request, 
                f"No se tienen instalados los pre-requisitos del sistema para esta integración: <br>"
                f"<b>Visual C++ 2012 Redistributable (x86)</b> <br>"
                f"<b>Visual C++ 2013 Redistributable (x86)</b> <br><hr class='my-1'>"
                f"consulte la <b>Guía de configuración</b> para continuar."
            )
            return redirect("agente:inicio")
        else:
            messages.error(request, "Hubo un problema al cargar la llave, consulte los logs para más detalles.")

        log(str(e), "error")
        return redirect("agente:log_agente")

    return redirect("agente:inicio")

def preview_voucher(request, id):
    tarea = Tarea.objects.get(id=id)
    tipo_transaccion = "Venta"
    if tarea.get_datos().get("codigo") == 5:
        tipo_transaccion = "Cancelación"

    return render(request, "agente/pdf/voucher_banorte.html", {
        "tarea": tarea,
        "configuracion": request.configuracion, 
        "tipo_transaccion": tipo_transaccion, 
    })

def imprimir_voucher(request, id):
    from .functions import imprimir_voucher_banorte


agente/templates/agente/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'agente/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static "agente/css/app.css" %}?v=1.1.3">
    <title>{{ title }} | Agente Admintotal</title>
    <link href="https://unpkg.com/ionicons@4.5.10-0/dist/css/ionicons.min.css" rel="stylesheet">
    
    <link rel="icon" type="image/png" href="{% static 'agente/img/favicon.png' %}">

    <script src="{% static 'agente/js/jquery-3.6.0.min.js' %}"></script>
    {% block extra_head %}
    {% endblock extra_head %}
  </head>
  <body>
    {% if request.configuracion.token %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light justify-content-between fixed-top border-bottom px-3">
      <a class="navbar-brand" href="{% url "agente:inicio" %}">
        <img src="{% static "agente/img/logo_azul_blanco.png" %}" width="30" height="30" class="d-inline-block align-top" alt="">
        Admintotal <small class="text-muted">v{{ SETTINGS.VERSION }}</small> 
      </a>
        
      <div>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav align-items-center">
            <li class="nav-item mx-2 actualizacion-disponible" style="display: none">
              <a class="nav-link active text-success font-weight-bold" href="{% url 'agente:guia_actualizacion' %}">Versión <span id="v"></span> disponible</span></a>
            </li>
            <li class="nav-item mx-2">
              <a class="nav-link {% if request.resolver_match.url_name == "inicio" %} active text-primary font-weight-bold {% endif %}" href="{% url "agente:inicio" %}">Inicio</a>
            </li>
            <li class="nav-item mx-2">
              <a class="nav-link {% if request.resolver_match.url_name == "tareas" %} active text-primary font-weight-bold {% endif %}" href="{% url "agente:tareas" %}">Tareas</a>
            </li>
            <li class="nav-item mx-2">
              <a class="nav-link {% if request.resolver_match.url_name == "log_agente" %} active text-primary font-weight-bold {% endif %}" href="{% url "agente:log_agente" %}">Logs</a>
            </li>
            <li class="nav-item mx-2 border-start ps-3">
              <div class="loading">
                <div class="spinner-border text-muted" role="status" style="position: absolute; height: 25px; width: 25px;margin-left:-3px;margin-top:-2px" >
                  <span class="visually-hidden">Loading...</span>
                </div>
              </div>
              <div class="dot-status"></div>
            </li>
            
            {% if SETTINGS.LOCAL_DEVELOPMENT %}
            <li class="nav-item mx-2 iniciar-agente" style="display:none">
              <a class="nav-link {% if request.resolver_match.url_name == "iniciar_agente" %} active text-primary font-weight-bold {% endif %}" href="{% url "agente:iniciar_agente" %}">Iniciar</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    {% endif %}

    {% include 'agente/includes/flash_messages.html' %}

    <div class="mt-4 py-5">
      {% block contenido %}
      {% endblock contenido %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{% static 'agente/js/popper.min.js' %}"></script>
    <script src="{% static 'agente/js/bootstrap.min.js' %}"></script>


    {% block js %}
    {% endblock js %}

    <script>
      function healthCheck() {
        $.ajax({
            url: "{% url 'agente:agente_health_check' %}",
            type: 'POST',
          }).done(function(res) {
            $(".dot-status").tooltip('dispose')

            $(".dot-status").attr("title", res.mensaje)            
            $(".dot-status").siblings(".loading").fadeOut("slow")

            if (res.status == "success") {
              $(".dot-status").attr("class", "dot-status bg-success")
              $(".dot-status").attr("title", "Agente en ejecución")
              
              $(".iniciar-agente").hide()
            } else {
              $(".dot-status").attr("class", "dot-status bg-danger")
              $(".iniciar-agente").show()
            }

            $(".dot-status").tooltip()
            setTimeout(healthCheck, 2000)
          }).fail(function(er) {
            setTimeout(healthCheck, 4000)
            $(".dot-status").tooltip('dispose')

            $(".dot-status").attr("class", "dot-status bg-danger")
            $(".dot-status").attr("title", "Error al consultar el estado del agente")
            $(".dot-status").tooltip()
          })
      }

      function validarUltimaVersion() {
        try {
          $.ajax({
            url: "{% url 'agente:validar_ultima_version' %}",
          }).done(function(res) {
            if (res.actualizacion_disponible) {
              $(".actualizacion-disponible #v").text(res.ultima_version)
              $(".actualizacion-disponible").fadeIn()
            }
          })
        } catch (error) {
          
        }
      }

        $(function() {
            $('[data-toggle="popover"]').popover()

            validarUltimaVersion()

            {% if request.configuracion.token %}
            healthCheck()
            {% endif %}

            $("[data-confirm]").click(function(e) {
              e.preventDefault()
              var url = $(this).attr("href")
              var mensaje = $(this).attr("data-confirm")
              if(confirm(mensaje)) {
                  window.location.href = url
              }
            })
        });
    </script>
  </body>
</html>

agente/templates/agente/configuracion_inicial.html
{% extends "agente/base.html" %}
{% load static %}

{% block contenido %}
<div class="container py-5">
	<div class="row justify-content-center">
		<div class="col-md-6">
			<div class="text-center mb-3">
				<img src="{% static "agente/img/logo_azul_blanco.png" %}" alt="Admintotal" class="img-fluid">
			</div>
			<div class="card card-body">
				<form action="." method="POST">
					{% csrf_token %}
					<div class="form-group">
						{{ form.clave.label_tag }}
						<div class="input-group">
							{{ form.clave }}
							<div class="input-group-append">
								<span class="input-group-text" id="basic-addon2">.{{ SETTINGS.ADMINTOTAL_HOST }}</span>
							</div>
						</div>					
						{{ form.clave.errors }}
					</div>
					<div class="form-group">
						{{ form.token.label_tag }}
						{{ form.token }}
						{{ form.token.errors }}
					</div>
					<div class="form-group text-right">
						<hr>
						<button class="btn btn-primary">Iniciar</button>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock contenido %}

agente/templates/agente/guia_actualizacion.html
{% extends "agente/base.html" %}
{% load static %}

{% block contenido %}

<div class="container-fluid my-2">
	<div class="row">
		<div class="col-md-12 text-center">
            <h3 class="text-info">Pasos para instalar la nueva versión del Agente Admintotal</h3>
            <hr>
            <div class="p-2">
                <div class="text-muted h5 my-1 mt-4">Paso 1</div>
                <a class="btn btn-success" href="https://gitlab.com/jahazieldom/agente-admintotal/-/raw/master/dist/Instalador-agente-admintotal.exe?inline=false">Descargar el instalador</a>
            </div>
            <div class="p-2">
                    <div class="text-muted h5 my-1 mt-4">Paso 2</div>
                    <a href="#" class="btn btn-danger detener-agente">Detener agente</a>
            </div>
            <div class="p-2">
                <div class="text-muted h5 my-1 mt-4">Paso 3</div>
                Click derecho en el instalador que descargamos en el Paso 1 y seleccionar "Ejecutar como administrador"
            </div>
            <div class="p-2">
                <div class="text-muted h5 my-1 mt-4">Paso 4</div>
                Una vez finalizada la actualización volver a iniciar el Agente (en el escritorio debe de estar un icono que dice "Agente Admintotal")
            </div>
		</div>
	</div>
</div>
<script>
$(function() {
    $(".detener-agente").click(function(e) {
        $.ajax({
            url: "{% url 'agente:detener_agente' %}",
            type: "POST",
        }).done(function(res) {
            console.log(res)
        })
    })

    $("[data-path]").click(function(e) {
        var path = $(this).attr("data-path")
        $.ajax({
            url: "{% url 'agente:abrir_explorador_archivos' %}",
            data: {path: path},
            type: "POST",
        }).done(function(res) {
            console.log(res)
        })
    })
})
</script>
{% endblock contenido %}

agente/templates/agente/guia_configuracion_banorte.html
{% extends "agente/base.html" %}
{% load static %}

{% block contenido %}

<div class="container-fluid my-2">
	<div class="row">
		<div class="col-md-12 text-center">
            <h3 class="text-info">Pasos para configurar terminales Banorte</h3>
            <hr>
            <div class="p-2">
                <div class="text-muted h5 my-1 mt-4">Paso 1</div>
                <div>Descargar e instalar driver para windows según sea el módelo de su terminal</div>
                <a class="btn btn-primary" target="_blank" href="https://soporte.admintotal.com/central_upload/arhivos_ticket/Driver_Pinpad_Win10.zip">Verifone vx810, vx820</a>
                <a class="btn btn-primary" target="_blank" href="https://soporte.admintotal.com/central_upload/archivos_ticket/Driver_Verifone.rar">Verifone P400</a>
            </div>
            <div class="p-2">
                <div class="text-muted h5 my-1 mt-4">Paso 2</div>
                <div>Descargar e instalar Visual C++ Redistributable para Visual Studio 2012 (x86)</div>
                <a class="btn btn-primary" target="_blank" href="https://www.microsoft.com/es-mx/download/details.aspx?id=30679">Descargar</a>
            </div>
            
            <div class="p-2">
                <div class="text-muted h5 my-1 mt-4">Paso 3</div>
                <div>Descargar e instalar Visual C++ Redistributable para Visual Studio 2013 (x86)</div>
                <a class="btn btn-primary" target="_blank" href="https://www.microsoft.com/es-mx/download/details.aspx?id=40784">Descargar</a>
            </div>
            
            <div class="p-2">
                <div class="text-muted h5 my-1 mt-4">Paso 4</div>
                Reiniciar la pc 
            </div>
            
            <div class="p-2">
                <div class="text-muted h5 my-1 mt-4">Paso 5</div>
                Una vez finalizados los pasos anteriores, configurar los parámetros de afiliación, usuario, password y puerto COM de la terminal. Hacer la carga de llave maestra en caso de ser solicitado por la terminal, para ello dar click en el botón "Cargar llave maestra"  que aparece en el apartado de <a href="/">configuración de banorte</a>
            </div>

		</div>
	</div>
</div>
<script>
$(function() {
    $(".detener-agente").click(function(e) {
        $.ajax({
            url: "{% url 'agente:detener_agente' %}",
            type: "POST",
        }).done(function(res) {
            console.log(res)
        })
    })

    $("[data-path]").click(function(e) {
        var path = $(this).attr("data-path")
        $.ajax({
            url: "{% url 'agente:abrir_explorador_archivos' %}",
            data: {path: path},
            type: "POST",
        }).done(function(res) {
            console.log(res)
        })
    })
})
</script>
{% endblock contenido %}

agente/templates/agente/logs.html
{% extends "agente/base.html" %}
{% load static %}

{% block contenido %}
<style>
pre{
    color: #cccccc;
    background-color: rgba(0,0,0,.2);
    padding: 10px;
    border-radius: 5px;
    height: 78vh;
    margin: 0;
    overflow: auto;
    font-size: .85em;

    white-space: pre-wrap;       /* Since CSS 2.1 */
    white-space: -moz-pre-wrap;  /* Mozilla, since 1999 */
    white-space: -pre-wrap;      /* Opera 4-6 */
    white-space: -o-pre-wrap;    /* Opera 7 */
    word-wrap: break-word;       /* Internet Explorer 5.5+ */
}
</style>
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
            <p class="text-center text-white">{{ log_file }}</p>
			<pre id="log">{{ log }}</pre>
		</div>
	</div>
</div>
<script>

function actualizarLogs() {
    $.ajax({
        url: "{{ request.path }}",
        data: {"tail": "{{ request.GET.tail|default:'' }}"}
    }).done(function(res) {
        if ($("#log").html() != res.log) {
            $("#log").html(res.log)
            $('#log').scrollTop($('#log')[0].scrollHeight);
            /*
            setTimeout(function() {
                actualizarLogs()
            }, 2000)
            */
        }
    })
}
$(function() {
    $('#log').scrollTop($('#log')[0].scrollHeight);
    actualizarLogs()
})
</script>
{% endblock contenido %}

agente/templates/agente/tareas.html
{% extends "agente/base.html" %}
{% load static %}

{% block contenido %}
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<div class="table-responsive">
				<table class="table table-striped table-borderless table-vm">
					<thead>
						<tr>
							<th>Status</th>
							<th>Descripción</th>
							<th>Inicio</th>
							<th>Fin</th>
							<th></th>
						</tr>
					</thead>
					<tbody>
						{% for tarea in objects %}
						<tr style="line-height: 1.1;">
							<td>
								{% if tarea.get_resultado.status == "success" %}
								<div class="badge bg-success"><i class="ion ion-md-checkmark"></i> {{ tarea.get_resultado.status }}</div>
								{% else %}
								<div class="badge bg-danger"><i class="ion ion-md-close"></i> {{ tarea.get_resultado.status }}</div>
								{% endif %}
							</td>
							<td>
								<b><a href="{% url 'agente:ver_tarea' tarea.id %}">{{ tarea.descripcion }}</a></b>
								{% if tarea.es_transaccion_pinpad %}
								<div>{{ tarea.get_datos.datos.referencia }} - ${{ tarea.get_datos.datos.monto }}</div>
								{% endif %}
								<div><small>{{ tarea.get_resultado.mensaje }}</small></div>
								
							</td>
							<td><a class="text-dark" href="{% url 'agente:ver_tarea' tarea.id %}">{{ tarea.inicio|date:"d/m/Y H:i:s" }}</a></td>
							<td><a class="text-dark" href="{% url 'agente:ver_tarea' tarea.id %}">{{ tarea.fin|date:"d/m/Y H:i:s" }}</a></td>
							<td class="text-end">
								{% if tarea.resultado_notificado %}
									<div class="text-success">Notificado</div>
								{% else %}
									<a href="{% url "agente:notificar_resultado_tarea" tarea.id %}" class="text-danger">No notificado</a>
									<a href="{% url "agente:notificar_resultado_tarea" tarea.id %}" class="text-danger">No notificado</a>
								{% endif %}
							</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
			{% include "utils/paginado.html" %}
		</div>
	</div>
</div>
{% endblock contenido %}

agente/templates/agente/ver_tarea.html
{% extends "agente/base.html" %}
{% load static %}

{% block contenido %}
<style>
pre{
    color: white;
    background-color: rgba(0,0,0,.2);
    padding: 10px;
    border-radius: 5px;
    height: 75vh;
    overflow: auto;
    font-size: .8em;

    white-space: pre-wrap;       /* Since CSS 2.1 */
    white-space: -moz-pre-wrap;  /* Mozilla, since 1999 */
    white-space: -pre-wrap;      /* Opera 4-6 */
    white-space: -o-pre-wrap;    /* Opera 7 */
    word-wrap: break-word;       /* Internet Explorer 5.5+ */
}
</style>
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
            <div class="d-flex flex-wrap align-items-center justify-content-between">
                <div class="d-flex">
                    <div class="p-2 m-1 font-weight-bold">{{ tarea.descripcion }}</div>
                    <div class="p-2 m-1 text-info">Inicio: {{ tarea.inicio|date:"d/m/Y H:i:s" }}</div>
                    <div class="p-2 m-1 text-info">Fin: {{ tarea.fin|date:"d/m/Y H:i:s" }}</div>
                </div>
                
                {% if transaccion_banorte %}
                <div class="d-flex">
                    
                    {% if SETTINGS.LOCAL_DEVELOPMENT %}                        
                    <div class="p-2 m-1"><a class="btn btn-primary btn-sm" href="{% url "agente:preview_voucher" tarea.id %}">Preview voucher</a></div>
                    {% endif %}
                    <div class="p-2 m-1"><a class="btn btn-primary btn-sm" href="{% url "agente:imprimir_voucher" tarea.id %}">Imprimir voucher</a></div>
                </div>
                {% endif %}
            </div>
			<pre id="log">{{ json_data }}</pre>
		</div>
	</div>
</div>
{% endblock contenido %}